from __future__ import annotations

import argparse
import asyncio
import csv
from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import statistics
import sys
from typing import Any
import warnings

from ragas import __version__ as ragas_version
from ragas.dataset_schema import SingleTurnSample
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper
from tqdm import tqdm
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from rageval.evaluation_metrics import (
    compute_answer_quality,
    compute_overall_quality,
    compute_reference_alignment,
    compute_retrieval_quality,
    default_formula_description,
    describe_custom_metric_rules,
    harmonic_mean,
    is_error_answer,
    is_numeric_question,
    numeric_tolerance_score,
    token_f1_score,
)
from rageval.evaluation_sharding import select_rows_for_shard
from rageval.utils import ensure_parent_dir

warnings.simplefilter("ignore", DeprecationWarning)

from ragas.metrics import (  # noqa: E402
    AnswerAccuracy,
    ContextEntityRecall,
    ExactMatch,
    Faithfulness,
    LLMContextPrecisionWithReference,
    LLMContextRecall,
    ResponseRelevancy,
    SemanticSimilarity,
)


SYSTEMS = ("vector", "lightrag")
PROFILES = ("deterministic", "balanced", "full")
CHUNK_MARKER_RE = re.compile(r"\[Chunk\s+\d+\]\s*")
DEFAULT_MANIFEST_PATH = Path("./dataset/processed/experiment/split_manifest.json")


@dataclass(slots=True)
class EvaluationConfig:
    input_csv: Path
    output_dir: Path
    metric_profile: str
    judge_model: str
    embedding_model: str
    openai_api_key: str | None
    openai_base_url: str | None
    max_retries: int
    metric_timeout_seconds: float
    limit: int | None
    manifest_path: Path | None
    num_shards: int | None
    shard_index: int | None


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate experiment_results.csv with Ragas metrics, custom metrics, and "
            "a paper-friendly composite scoring formula."
        )
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path("./results/experiment_results.csv"),
        help="CSV generated by run_experiment.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory for evaluation outputs. Defaults to ./results/evaluation/<input-stem>/<profile>.",
    )
    parser.add_argument(
        "--metric-profile",
        choices=PROFILES,
        default="balanced",
        help=(
            "deterministic = no external judge calls, "
            "balanced = answer-quality metrics, "
            "full = balanced + retrieval metrics."
        ),
    )
    parser.add_argument(
        "--judge-model",
        default=None,
        help="Judge model used by Ragas LLM metrics. Defaults to RAGEVAL_JUDGE_MODEL or gpt-4o-mini.",
    )
    parser.add_argument(
        "--embedding-model",
        default=None,
        help="Embedding model used by semantic similarity. Defaults to RAGEVAL_EMBEDDING_MODEL or text-embedding-3-small.",
    )
    parser.add_argument("--openai-api-key", default=None)
    parser.add_argument("--openai-base-url", default=None)
    parser.add_argument("--max-retries", type=int, default=2)
    parser.add_argument("--metric-timeout-seconds", type=float, default=120.0)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--num-shards", type=int, default=None)
    parser.add_argument("--shard-index", type=int, default=None)
    parser.add_argument(
        "--manifest-path",
        type=Path,
        default=DEFAULT_MANIFEST_PATH,
        help="Optional split_manifest.json used to tag stress documents.",
    )
    return parser.parse_args(argv)


def build_config(args: argparse.Namespace) -> EvaluationConfig:
    judge_model = args.judge_model or os.getenv("RAGEVAL_JUDGE_MODEL") or "gpt-4o-mini"
    embedding_model = (
        args.embedding_model
        or os.getenv("RAGEVAL_EMBEDDING_MODEL")
        or "text-embedding-3-small"
    )
    output_dir = args.output_dir
    if output_dir is None:
        output_dir = Path("./results/evaluation") / args.input_csv.stem / args.metric_profile
    manifest_path = args.manifest_path if args.manifest_path and args.manifest_path.exists() else None
    return EvaluationConfig(
        input_csv=args.input_csv,
        output_dir=output_dir,
        metric_profile=args.metric_profile,
        judge_model=judge_model,
        embedding_model=embedding_model,
        openai_api_key=args.openai_api_key or os.getenv("OPENAI_API_KEY"),
        openai_base_url=args.openai_base_url or os.getenv("OPENAI_BASE_URL"),
        max_retries=args.max_retries,
        metric_timeout_seconds=args.metric_timeout_seconds,
        limit=args.limit,
        manifest_path=manifest_path,
        num_shards=args.num_shards,
        shard_index=args.shard_index,
    )


def compose_user_input(row: dict[str, str]) -> str:
    instruction = (row.get("instruction") or "").strip()
    question = (row.get("question") or "").strip()
    if instruction and question:
        return f"Instruction:\n{instruction}\n\nQuestion:\n{question}"
    return instruction or question


def split_retrieved_context(raw_context: str) -> list[str]:
    text = (raw_context or "").strip()
    if not text:
        return []
    if "[Chunk" not in text:
        return [text]
    pieces = CHUNK_MARKER_RE.split(text)
    return [piece.strip() for piece in pieces if piece.strip()]


def safe_int(value: str | int | None) -> int:
    try:
        return int(str(value or "0"))
    except ValueError:
        return 0


def safe_float(value: str | float | int | None) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except ValueError:
        return None


def load_input_rows(path: Path, limit: int | None = None) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Input CSV not found: {path}")

    csv.field_size_limit(sys.maxsize)
    rows: list[dict[str, str]] = []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for index, row in enumerate(reader, start=1):
            rows.append({key: value or "" for key, value in row.items()})
            if limit is not None and index >= limit:
                break
    return rows


def load_completed_pairs(details_csv: Path) -> set[tuple[str, str]]:
    if not details_csv.exists():
        return set()

    csv.field_size_limit(sys.maxsize)
    completed: set[tuple[str, str]] = set()
    with details_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            doc_id = (row.get("doc_id") or "").strip()
            q_id = (row.get("q_id") or "").strip()
            if doc_id and q_id:
                completed.add((doc_id, q_id))
    return completed


def load_stress_doc_ids(manifest_path: Path | None) -> set[str]:
    if manifest_path is None or not manifest_path.exists():
        return set()
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    return {
        str(item.get("doc_id"))
        for item in payload.get("stress_test_doc_ids", [])
        if isinstance(item, dict) and item.get("doc_id")
    }


def assign_length_buckets(
    input_rows: list[dict[str, str]],
    stress_doc_ids: set[str],
) -> dict[tuple[str, str], dict[str, str]]:
    unique_docs: dict[tuple[str, str], dict[str, Any]] = {}
    for row in input_rows:
        key = (row.get("dataset_name", ""), row.get("doc_id", ""))
        if key not in unique_docs:
            unique_docs[key] = {
                "dataset_name": key[0],
                "doc_id": key[1],
                "doc_length_tokens": safe_int(row.get("doc_length_tokens")),
            }

    annotations: dict[tuple[str, str], dict[str, str]] = {}
    grouped: dict[str, list[dict[str, Any]]] = {}

    for key, item in unique_docs.items():
        if item["doc_id"] in stress_doc_ids:
            annotations[key] = {
                "evaluation_set": "stress",
                "length_bucket": "stress",
            }
            continue
        grouped.setdefault(item["dataset_name"], []).append(item)

    for dataset_name, docs in grouped.items():
        docs_sorted = sorted(
            docs,
            key=lambda item: (item["doc_length_tokens"], item["doc_id"]),
        )
        n_docs = len(docs_sorted)
        base_size = n_docs // 3
        remainder = n_docs % 3
        bucket_sizes = [base_size + (1 if index < remainder else 0) for index in range(3)]

        start = 0
        for label, size in zip(("short", "medium", "long"), bucket_sizes, strict=True):
            end = start + size
            for item in docs_sorted[start:end]:
                annotations[(dataset_name, item["doc_id"])] = {
                    "evaluation_set": "main_or_unknown",
                    "length_bucket": label,
                }
            start = end

    return annotations


def details_csv_headers() -> list[str]:
    headers = [
        "dataset_name",
        "split",
        "domain",
        "language",
        "level",
        "set_id",
        "doc_id",
        "q_id",
        "evaluation_set",
        "length_bucket",
        "doc_length_tokens",
        "question_type",
        "instruction",
        "question",
        "ground_truth",
    ]
    for system in SYSTEMS:
        headers.extend(
            [
                f"{system}_answer",
                f"{system}_is_error",
                f"{system}_exact_match",
                f"{system}_token_f1_score",
                f"{system}_numeric_tolerance_score",
                f"{system}_semantic_similarity",
                f"{system}_answer_accuracy",
                f"{system}_faithfulness",
                f"{system}_response_relevancy",
                f"{system}_context_precision",
                f"{system}_context_recall",
                f"{system}_context_entity_recall",
                f"{system}_context_pr_f1",
                f"{system}_reference_alignment_score",
                f"{system}_answer_quality_score",
                f"{system}_retrieval_quality_score",
                f"{system}_overall_quality_score",
                f"{system}_metric_errors",
            ]
        )
    headers.extend(
        [
            "answer_quality_diff_lightrag_minus_vector",
            "retrieval_quality_diff_lightrag_minus_vector",
            "overall_quality_diff_lightrag_minus_vector",
        ]
    )
    return headers


def open_details_writer(details_csv: Path) -> tuple[Any, csv.DictWriter]:
    ensure_parent_dir(details_csv)
    needs_header = not details_csv.exists() or details_csv.stat().st_size == 0
    handle = details_csv.open("a", encoding="utf-8-sig", newline="")
    writer = csv.DictWriter(handle, fieldnames=details_csv_headers())
    if needs_header:
        writer.writeheader()
        handle.flush()
    return handle, writer


class MetricSuite:
    def __init__(self, config: EvaluationConfig) -> None:
        self.config = config
        self.metrics: dict[str, Any] = {
            "exact_match": ExactMatch(),
        }
        self._llm_metrics_enabled = config.metric_profile in {"balanced", "full"}
        self._context_metrics_enabled = config.metric_profile == "full"

        if not self._llm_metrics_enabled:
            return

        if not config.openai_api_key:
            raise ValueError(
                "OPENAI_API_KEY is required for balanced/full evaluation profiles."
            )

        langchain_llm = ChatOpenAI(
            model=config.judge_model,
            api_key=config.openai_api_key,
            base_url=config.openai_base_url,
            timeout=config.metric_timeout_seconds,
            max_retries=config.max_retries,
            temperature=0.01,
        )
        llm = LangchainLLMWrapper(langchain_llm)

        langchain_embeddings = OpenAIEmbeddings(
            model=config.embedding_model,
            api_key=config.openai_api_key,
            base_url=config.openai_base_url,
            max_retries=config.max_retries,
        )
        embeddings = LangchainEmbeddingsWrapper(langchain_embeddings)

        self.metrics.update(
            {
                "semantic_similarity": SemanticSimilarity(embeddings=embeddings),
                "answer_accuracy": AnswerAccuracy(llm=llm),
                "faithfulness": Faithfulness(llm=llm),
                "response_relevancy": ResponseRelevancy(llm=llm, embeddings=embeddings),
            }
        )

        if self._context_metrics_enabled:
            self.metrics.update(
                {
                    "context_precision": LLMContextPrecisionWithReference(llm=llm),
                    "context_recall": LLMContextRecall(llm=llm),
                    "context_entity_recall": ContextEntityRecall(),
                }
            )

    def has_metric(self, name: str) -> bool:
        return name in self.metrics

    async def score_builtin_metric(
        self,
        name: str,
        sample: SingleTurnSample,
    ) -> float:
        metric = self.metrics[name]
        return await metric.single_turn_ascore(
            sample,
            timeout=self.config.metric_timeout_seconds,
        )


def _extract_metric_value(metric_result: Any) -> float | None:
    value = getattr(metric_result, "value", metric_result)
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


async def evaluate_system_row(
    *,
    system: str,
    row: dict[str, str],
    metric_suite: MetricSuite,
    question_is_numeric: bool,
) -> dict[str, Any]:
    answer = row.get(f"{system}_answer", "")
    retrieved_context = row.get(f"{system}_retrieved_context", "")
    user_input = compose_user_input(row)
    reference = row.get("ground_truth", "")
    contexts = split_retrieved_context(retrieved_context)
    sample = SingleTurnSample(
        user_input=user_input,
        response=answer,
        reference=reference,
        retrieved_contexts=contexts,
    )

    results: dict[str, float | None] = {
        "exact_match": None,
        "token_f1_score": None,
        "numeric_tolerance_score": None,
        "semantic_similarity": None,
        "answer_accuracy": None,
        "faithfulness": None,
        "response_relevancy": None,
        "context_precision": None,
        "context_recall": None,
        "context_entity_recall": None,
        "context_pr_f1": None,
        "reference_alignment_score": None,
        "answer_quality_score": None,
        "retrieval_quality_score": None,
        "overall_quality_score": None,
    }
    errors: dict[str, str] = {}

    results["token_f1_score"] = _extract_metric_value(
        token_f1_score.score(response=answer, reference=reference)
    )
    if question_is_numeric:
        results["numeric_tolerance_score"] = _extract_metric_value(
            numeric_tolerance_score.score(response=answer, reference=reference)
        )

    try:
        results["exact_match"] = await metric_suite.score_builtin_metric("exact_match", sample)
    except Exception as exc:  # pragma: no cover - external library / API
        errors["exact_match"] = str(exc)

    expensive_answer_metrics_allowed = not is_error_answer(answer)

    if expensive_answer_metrics_allowed and metric_suite.has_metric("semantic_similarity"):
        try:
            results["semantic_similarity"] = await metric_suite.score_builtin_metric(
                "semantic_similarity",
                sample,
            )
        except Exception as exc:  # pragma: no cover - external library / API
            errors["semantic_similarity"] = str(exc)
    elif metric_suite.has_metric("semantic_similarity"):
        results["semantic_similarity"] = 0.0

    for name in ("answer_accuracy", "response_relevancy"):
        if not metric_suite.has_metric(name):
            continue
        if not expensive_answer_metrics_allowed:
            results[name] = 0.0
            continue
        try:
            results[name] = await metric_suite.score_builtin_metric(name, sample)
        except Exception as exc:  # pragma: no cover - external library / API
            errors[name] = str(exc)

    if metric_suite.has_metric("faithfulness"):
        if not expensive_answer_metrics_allowed or not contexts:
            results["faithfulness"] = 0.0
        else:
            try:
                results["faithfulness"] = await metric_suite.score_builtin_metric(
                    "faithfulness",
                    sample,
                )
            except Exception as exc:  # pragma: no cover - external library / API
                errors["faithfulness"] = str(exc)

    if metric_suite.has_metric("context_precision"):
        if not contexts:
            results["context_precision"] = 0.0
            results["context_recall"] = 0.0
            results["context_entity_recall"] = 0.0
        else:
            for name in ("context_precision", "context_recall", "context_entity_recall"):
                try:
                    results[name] = await metric_suite.score_builtin_metric(name, sample)
                except Exception as exc:  # pragma: no cover - external library / API
                    errors[name] = str(exc)
        results["context_pr_f1"] = harmonic_mean(
            results["context_precision"],
            results["context_recall"],
        )

    results["reference_alignment_score"] = compute_reference_alignment(
        is_numeric=question_is_numeric,
        answer_accuracy=results["answer_accuracy"],
        semantic_similarity=results["semantic_similarity"],
        exact_match=results["exact_match"],
        token_f1=results["token_f1_score"],
        numeric_tolerance=results["numeric_tolerance_score"],
    )
    results["answer_quality_score"] = compute_answer_quality(
        reference_alignment=results["reference_alignment_score"],
        faithfulness=results["faithfulness"],
        response_relevancy=results["response_relevancy"],
    )
    results["retrieval_quality_score"] = compute_retrieval_quality(
        context_precision=results["context_precision"],
        context_recall=results["context_recall"],
        context_entity_recall=results["context_entity_recall"],
    )
    results["overall_quality_score"] = compute_overall_quality(
        answer_quality=results["answer_quality_score"],
        retrieval_quality=results["retrieval_quality_score"],
    )

    return {
        "answer": answer,
        "is_error": is_error_answer(answer),
        "scores": results,
        "errors": errors,
    }


def build_detail_row(
    row: dict[str, str],
    annotations: dict[tuple[str, str], dict[str, str]],
    vector_result: dict[str, Any],
    lightrag_result: dict[str, Any],
) -> dict[str, Any]:
    key = (row.get("dataset_name", ""), row.get("doc_id", ""))
    annotation = annotations.get(
        key,
        {
            "evaluation_set": "main_or_unknown",
            "length_bucket": "unknown",
        },
    )
    question_is_numeric = is_numeric_question(
        compose_user_input(row),
        row.get("ground_truth", ""),
    )

    detail_row: dict[str, Any] = {
        "dataset_name": row.get("dataset_name", ""),
        "split": row.get("split", ""),
        "domain": row.get("domain", ""),
        "language": row.get("language", ""),
        "level": row.get("level", ""),
        "set_id": row.get("set_id", ""),
        "doc_id": row.get("doc_id", ""),
        "q_id": row.get("q_id", ""),
        "evaluation_set": annotation["evaluation_set"],
        "length_bucket": annotation["length_bucket"],
        "doc_length_tokens": row.get("doc_length_tokens", ""),
        "question_type": "numeric" if question_is_numeric else "textual",
        "instruction": row.get("instruction", ""),
        "question": row.get("question", ""),
        "ground_truth": row.get("ground_truth", ""),
    }

    for system, result in (("vector", vector_result), ("lightrag", lightrag_result)):
        detail_row[f"{system}_answer"] = result["answer"]
        detail_row[f"{system}_is_error"] = "1" if result["is_error"] else "0"
        for metric_name, metric_value in result["scores"].items():
            detail_row[f"{system}_{metric_name}"] = (
                "" if metric_value is None else f"{metric_value:.6f}"
            )
        detail_row[f"{system}_metric_errors"] = (
            json.dumps(result["errors"], ensure_ascii=False, sort_keys=True)
            if result["errors"]
            else ""
        )

    for metric_name, column_name in (
        ("answer_quality_score", "answer_quality_diff_lightrag_minus_vector"),
        ("retrieval_quality_score", "retrieval_quality_diff_lightrag_minus_vector"),
        ("overall_quality_score", "overall_quality_diff_lightrag_minus_vector"),
    ):
        vector_value = vector_result["scores"].get(metric_name)
        lightrag_value = lightrag_result["scores"].get(metric_name)
        if vector_value is None or lightrag_value is None:
            detail_row[column_name] = ""
        else:
            detail_row[column_name] = f"{(lightrag_value - vector_value):.6f}"

    return detail_row


def load_detail_rows(details_csv: Path) -> list[dict[str, str]]:
    if not details_csv.exists():
        return []
    with details_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        return [{key: value or "" for key, value in row.items()} for row in csv.DictReader(handle)]


def flatten_detail_rows(detail_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    flattened: list[dict[str, Any]] = []
    metric_fields = [
        "exact_match",
        "token_f1_score",
        "numeric_tolerance_score",
        "semantic_similarity",
        "answer_accuracy",
        "faithfulness",
        "response_relevancy",
        "context_precision",
        "context_recall",
        "context_entity_recall",
        "context_pr_f1",
        "reference_alignment_score",
        "answer_quality_score",
        "retrieval_quality_score",
        "overall_quality_score",
    ]

    for row in detail_rows:
        for system in SYSTEMS:
            item: dict[str, Any] = {
                "system": system,
                "dataset_name": row.get("dataset_name", ""),
                "split": row.get("split", ""),
                "domain": row.get("domain", ""),
                "language": row.get("language", ""),
                "level": row.get("level", ""),
                "set_id": row.get("set_id", ""),
                "doc_id": row.get("doc_id", ""),
                "q_id": row.get("q_id", ""),
                "evaluation_set": row.get("evaluation_set", ""),
                "length_bucket": row.get("length_bucket", ""),
                "question_type": row.get("question_type", ""),
                "doc_length_tokens": safe_int(row.get("doc_length_tokens")),
                "is_error": row.get(f"{system}_is_error", "") == "1",
            }
            for metric_name in metric_fields:
                item[metric_name] = safe_float(row.get(f"{system}_{metric_name}"))
            flattened.append(item)
    return flattened


def aggregate_rows(
    rows: list[dict[str, Any]],
    group_fields: list[str],
) -> list[dict[str, Any]]:
    metric_fields = [
        "exact_match",
        "token_f1_score",
        "numeric_tolerance_score",
        "semantic_similarity",
        "answer_accuracy",
        "faithfulness",
        "response_relevancy",
        "context_precision",
        "context_recall",
        "context_entity_recall",
        "context_pr_f1",
        "reference_alignment_score",
        "answer_quality_score",
        "retrieval_quality_score",
        "overall_quality_score",
    ]

    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = {}
    for row in rows:
        key = tuple(row.get(field, "") for field in group_fields)
        grouped.setdefault(key, []).append(row)

    output_rows: list[dict[str, Any]] = []
    for key, group in sorted(grouped.items()):
        item = {field: value for field, value in zip(group_fields, key, strict=True)}
        item["row_count"] = len(group)
        item["error_row_count"] = sum(1 for row in group if row["is_error"])
        item["numeric_question_count"] = sum(
            1 for row in group if row.get("question_type") == "numeric"
        )
        for metric_name in metric_fields:
            values = [row[metric_name] for row in group if row.get(metric_name) is not None]
            item[metric_name] = "" if not values else f"{statistics.fmean(values):.6f}"
        output_rows.append(item)
    return output_rows


def write_summary_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    ensure_parent_dir(path)
    if not rows:
        with path.open("w", encoding="utf-8-sig", newline="") as handle:
            handle.write("")
        return
    headers = list(rows[0].keys())
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)


def write_methodology_json(path: Path, config: EvaluationConfig) -> None:
    formulas = default_formula_description()
    payload = {
        "ragas_version": ragas_version,
        "metric_profile": config.metric_profile,
        "input_csv": str(config.input_csv),
        "judge_model": config.judge_model,
        "embedding_model": config.embedding_model,
        "openai_base_url": config.openai_base_url or "",
        "formula": {
            "reference_alignment_numeric": (
                "0.55 * NumericTolerance + 0.25 * AnswerAccuracy + "
                "0.10 * TokenF1 + 0.10 * ExactMatch"
            ),
            "reference_alignment_textual": (
                "0.45 * AnswerAccuracy + 0.25 * SemanticSimilarity + "
                "0.20 * TokenF1 + 0.10 * ExactMatch"
            ),
            "answer_quality": formulas.answer_quality,
            "retrieval_quality": formulas.retrieval_quality,
            "overall_quality": formulas.overall_quality,
        },
        "custom_metric_rules": describe_custom_metric_rules(),
    }
    ensure_parent_dir(path)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


async def main_async(config: EvaluationConfig) -> None:
    input_rows = load_input_rows(config.input_csv, limit=config.limit)
    stress_doc_ids = load_stress_doc_ids(config.manifest_path)
    annotations = assign_length_buckets(input_rows, stress_doc_ids)
    shard_rows = select_rows_for_shard(
        input_rows,
        num_shards=config.num_shards,
        shard_index=config.shard_index,
    )

    metric_suite = MetricSuite(config)
    details_csv = config.output_dir / "evaluation_details.csv"
    details_handle, details_writer = open_details_writer(details_csv)
    completed_pairs = load_completed_pairs(details_csv)

    try:
        for row in tqdm(shard_rows, desc="Evaluating rows", unit="qa"):
            pair = (row.get("doc_id", ""), row.get("q_id", ""))
            if pair in completed_pairs:
                continue

            question_is_numeric = is_numeric_question(
                compose_user_input(row),
                row.get("ground_truth", ""),
            )
            vector_result = await evaluate_system_row(
                system="vector",
                row=row,
                metric_suite=metric_suite,
                question_is_numeric=question_is_numeric,
            )
            lightrag_result = await evaluate_system_row(
                system="lightrag",
                row=row,
                metric_suite=metric_suite,
                question_is_numeric=question_is_numeric,
            )

            details_writer.writerow(
                build_detail_row(
                    row=row,
                    annotations=annotations,
                    vector_result=vector_result,
                    lightrag_result=lightrag_result,
                )
            )
            details_handle.flush()
            completed_pairs.add(pair)
    finally:
        details_handle.close()

    detail_rows = load_detail_rows(details_csv)
    flattened_rows = flatten_detail_rows(detail_rows)

    write_summary_csv(
        config.output_dir / "evaluation_doc_summary.csv",
        aggregate_rows(
            flattened_rows,
            group_fields=[
                "system",
                "dataset_name",
                "doc_id",
                "evaluation_set",
                "length_bucket",
            ],
        ),
    )
    write_summary_csv(
        config.output_dir / "evaluation_bucket_summary.csv",
        aggregate_rows(
            flattened_rows,
            group_fields=["system", "dataset_name", "evaluation_set", "length_bucket"],
        ),
    )
    write_summary_csv(
        config.output_dir / "evaluation_dataset_summary.csv",
        aggregate_rows(
            flattened_rows,
            group_fields=["system", "dataset_name", "evaluation_set"],
        ),
    )
    write_summary_csv(
        config.output_dir / "evaluation_overall_summary.csv",
        aggregate_rows(
            flattened_rows,
            group_fields=["system"],
        ),
    )
    write_methodology_json(config.output_dir / "methodology.json", config)


def main() -> None:
    args = parse_args()
    config = build_config(args)
    asyncio.run(main_async(config))


if __name__ == "__main__":
    main()
