from __future__ import annotations

import argparse
from collections import defaultdict
import csv
import json
import math
from math import isnan
from pathlib import Path
import statistics
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from scipy import stats

from rageval.utils import ensure_parent_dir


MAIN_LENGTH_BUCKETS = ("short", "medium", "long")
SYSTEMS = ("vector", "lightrag")
SYSTEM_LABELS = {
    "vector": "VectorRAG",
    "lightrag": "LightRAG",
}
SYSTEM_COLORS = {
    "vector": "#1f4e79",
    "lightrag": "#b85c38",
}
EXPERIMENT_MARKERS = {
    "main": "o",
    "stress": "s",
    "ultra": "^",
}
DEFAULT_METRIC = "answer_quality_score"
PRE_FORMULA_ANSWER_METRICS = [
    "exact_match",
    "token_f1_score",
    "numeric_tolerance_score",
    "semantic_similarity",
    "answer_accuracy",
    "faithfulness",
    "response_relevancy",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate thesis tables, statistical tests, and charts from a Ragas evaluation output directory."
        )
    )
    parser.add_argument(
        "--evaluation-dir",
        type=Path,
        required=True,
        help="Directory generated by scripts/evaluate_with_ragas.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for tables/figures. Defaults to <evaluation-dir>/analysis.",
    )
    parser.add_argument(
        "--token-usage-jsonl",
        type=Path,
        default=Path("./results/token_usage.jsonl"),
        help="Optional token usage JSONL for cost proxy analysis.",
    )
    parser.add_argument(
        "--main-metric",
        default=DEFAULT_METRIC,
        choices=(
            "answer_quality_score",
            "retrieval_quality_score",
            "overall_quality_score",
            "exact_match",
            "answer_accuracy",
            "faithfulness",
            "response_relevancy",
        ),
        help="Metric used in main charts and paired tests.",
    )
    parser.add_argument(
        "--extra-evaluation-dirs",
        nargs="*",
        type=Path,
        default=None,
        help=(
            "Optional extra evaluation directories to merge into the token-length "
            "scatter plot for all experiments."
        ),
    )
    return parser.parse_args()


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Required CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [{key: value or "" for key, value in row.items()} for row in csv.DictReader(handle)]


def safe_float(value: str | float | int | None) -> float | None:
    if value in (None, ""):
        return None
    try:
        parsed = float(value)
    except ValueError:
        return None
    if isnan(parsed):
        return None
    return parsed


def safe_int(value: str | int | None) -> int:
    try:
        return int(str(value or "0"))
    except ValueError:
        return 0


def mean_or_none(values: list[float]) -> float | None:
    return None if not values else statistics.fmean(values)


def std_or_none(values: list[float]) -> float | None:
    if len(values) < 2:
        return None
    return statistics.stdev(values)


def flatten_doc_rows(doc_summary_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    numeric_fields = [
        "exact_match",
        "token_f1_score",
        "numeric_tolerance_score",
        "semantic_similarity",
        "answer_accuracy",
        "faithfulness",
        "response_relevancy",
        "context_precision",
        "context_recall",
        "context_entity_recall",
        "context_pr_f1",
        "reference_alignment_score",
        "answer_quality_score",
        "retrieval_quality_score",
        "overall_quality_score",
    ]
    rows: list[dict[str, Any]] = []
    for row in doc_summary_rows:
        item: dict[str, Any] = {
            "system": row.get("system", ""),
            "dataset_name": row.get("dataset_name", ""),
            "doc_id": row.get("doc_id", ""),
            "evaluation_set": row.get("evaluation_set", ""),
            "length_bucket": row.get("length_bucket", ""),
            "row_count": safe_int(row.get("row_count")),
            "error_row_count": safe_int(row.get("error_row_count")),
            "numeric_question_count": safe_int(row.get("numeric_question_count")),
            "avg_error_question_rate": 0.0,
            "avg_numeric_question_share": 0.0,
        }
        if item["row_count"] > 0:
            item["avg_error_question_rate"] = item["error_row_count"] / item["row_count"]
            item["avg_numeric_question_share"] = (
                item["numeric_question_count"] / item["row_count"]
            )
        for field in numeric_fields:
            item[field] = safe_float(row.get(field))
        rows.append(item)
    return rows


def flatten_detail_rows(detail_rows: list[dict[str, str]]) -> list[dict[str, Any]]:
    numeric_fields = [
        "exact_match",
        "token_f1_score",
        "numeric_tolerance_score",
        "semantic_similarity",
        "answer_accuracy",
        "faithfulness",
        "response_relevancy",
        "context_precision",
        "context_recall",
        "context_entity_recall",
        "context_pr_f1",
        "reference_alignment_score",
        "answer_quality_score",
        "retrieval_quality_score",
        "overall_quality_score",
    ]
    rows: list[dict[str, Any]] = []
    for row in detail_rows:
        for system in SYSTEMS:
            item: dict[str, Any] = {
                "system": system,
                "dataset_name": row.get("dataset_name", ""),
                "split": row.get("split", ""),
                "domain": row.get("domain", ""),
                "language": row.get("language", ""),
                "doc_id": row.get("doc_id", ""),
                "q_id": row.get("q_id", ""),
                "evaluation_set": row.get("evaluation_set", ""),
                "length_bucket": row.get("length_bucket", ""),
                "question_type": row.get("question_type", ""),
                "doc_length_tokens": safe_int(row.get("doc_length_tokens")),
                "is_error": row.get(f"{system}_is_error", "") == "1",
            }
            for field in numeric_fields:
                item[field] = safe_float(row.get(f"{system}_{field}"))
            rows.append(item)
    return rows


def infer_experiment_source(row: dict[str, Any]) -> str:
    dataset_name = str(row.get("dataset_name", ""))
    evaluation_set = str(row.get("evaluation_set", ""))
    if dataset_name == "UltraLongFinance":
        return "ultra"
    if evaluation_set == "stress":
        return "stress"
    return "main"


def build_doc_metric_points(
    detail_rows: list[dict[str, Any]],
    metric_name: str,
) -> list[dict[str, Any]]:
    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = defaultdict(list)
    for row in detail_rows:
        key = (
            row.get("system", ""),
            row.get("dataset_name", ""),
            row.get("doc_id", ""),
            row.get("evaluation_set", ""),
            row.get("length_bucket", ""),
            row.get("doc_length_tokens", 0),
        )
        grouped[key].append(row)

    output: list[dict[str, Any]] = []
    for key, group in grouped.items():
        values = [row[metric_name] for row in group if row.get(metric_name) is not None]
        if not values:
            continue
        system, dataset_name, doc_id, evaluation_set, length_bucket, doc_length_tokens = key
        output.append(
            {
                "system": system,
                "dataset_name": dataset_name,
                "doc_id": doc_id,
                "evaluation_set": evaluation_set,
                "length_bucket": length_bucket,
                "doc_length_tokens": int(doc_length_tokens),
                metric_name: mean_or_none(values),
                "experiment_source": infer_experiment_source(
                    {
                        "dataset_name": dataset_name,
                        "evaluation_set": evaluation_set,
                    }
                ),
            }
        )
    return output


def load_merged_detail_rows(
    primary_evaluation_dir: Path,
    extra_evaluation_dirs: list[Path] | None = None,
) -> list[dict[str, Any]]:
    detail_rows = flatten_detail_rows(load_csv_rows(primary_evaluation_dir / "evaluation_details.csv"))
    for extra_dir in extra_evaluation_dirs or []:
        detail_rows.extend(flatten_detail_rows(load_csv_rows(extra_dir / "evaluation_details.csv")))
    return detail_rows


def aggregate_rows(
    rows: list[dict[str, Any]],
    group_fields: list[str],
    metric_fields: list[str],
    extra_fields: list[str] | None = None,
) -> list[dict[str, Any]]:
    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        key = tuple(row.get(field, "") for field in group_fields)
        grouped[key].append(row)

    output_rows: list[dict[str, Any]] = []
    for key, group in sorted(grouped.items()):
        item = {field: value for field, value in zip(group_fields, key, strict=True)}
        item["count"] = len(group)
        for field in metric_fields:
            values = [row[field] for row in group if row.get(field) is not None]
            item[field] = mean_or_none(values)
        if extra_fields:
            for field in extra_fields:
                values = [row[field] for row in group if row.get(field) is not None]
                item[field] = mean_or_none(values)
        output_rows.append(item)
    return output_rows


def format_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    ensure_parent_dir(path)
    if not rows:
        with path.open("w", encoding="utf-8-sig", newline="") as handle:
            handle.write("")
        return
    headers = list(rows[0].keys())
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: format_cell(value) for key, value in row.items()})


def write_markdown(path: Path, rows: list[dict[str, Any]]) -> None:
    ensure_parent_dir(path)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    headers = list(rows[0].keys())
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(format_cell(row.get(header)) for header in headers) + " |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_table_bundle(base_path: Path, rows: list[dict[str, Any]]) -> None:
    write_csv(base_path.with_suffix(".csv"), rows)
    write_markdown(base_path.with_suffix(".md"), rows)


def pair_doc_metric_rows(
    doc_rows: list[dict[str, Any]],
    metric_name: str,
) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str, str, str], dict[str, dict[str, Any]]] = defaultdict(dict)
    for row in doc_rows:
        key = (
            row.get("dataset_name", ""),
            row.get("doc_id", ""),
            row.get("evaluation_set", ""),
            row.get("length_bucket", ""),
        )
        grouped[key][row.get("system", "")] = row

    paired: list[dict[str, Any]] = []
    for (dataset_name, doc_id, evaluation_set, length_bucket), systems in grouped.items():
        vector_row = systems.get("vector")
        lightrag_row = systems.get("lightrag")
        if vector_row is None or lightrag_row is None:
            continue
        vector_value = vector_row.get(metric_name)
        lightrag_value = lightrag_row.get(metric_name)
        if vector_value is None or lightrag_value is None:
            continue
        paired.append(
            {
                "dataset_name": dataset_name,
                "doc_id": doc_id,
                "evaluation_set": evaluation_set,
                "length_bucket": length_bucket,
                "vector_value": vector_value,
                "lightrag_value": lightrag_value,
                "diff_lightrag_minus_vector": lightrag_value - vector_value,
            }
        )
    return paired


def _paired_test_result(
    group_name: str,
    paired_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    vector_values = [row["vector_value"] for row in paired_rows]
    lightrag_values = [row["lightrag_value"] for row in paired_rows]
    diffs = [row["diff_lightrag_minus_vector"] for row in paired_rows]

    result: dict[str, Any] = {
        "group": group_name,
        "paired_doc_count": len(paired_rows),
        "vector_mean": mean_or_none(vector_values),
        "lightrag_mean": mean_or_none(lightrag_values),
        "mean_diff_lightrag_minus_vector": mean_or_none(diffs),
        "std_diff": std_or_none(diffs),
        "cohen_dz": None,
        "paired_t_pvalue": None,
        "wilcoxon_pvalue": None,
        "better_system": "",
    }

    if result["mean_diff_lightrag_minus_vector"] is not None:
        if result["mean_diff_lightrag_minus_vector"] > 0:
            result["better_system"] = "LightRAG"
        elif result["mean_diff_lightrag_minus_vector"] < 0:
            result["better_system"] = "VectorRAG"
        else:
            result["better_system"] = "Tie"

    if result["std_diff"] not in (None, 0):
        result["cohen_dz"] = result["mean_diff_lightrag_minus_vector"] / result["std_diff"]

    if len(diffs) >= 2:
        try:
            result["paired_t_pvalue"] = stats.ttest_rel(
                lightrag_values,
                vector_values,
                nan_policy="omit",
            ).pvalue
        except Exception:
            result["paired_t_pvalue"] = None

        try:
            if all(diff == 0 for diff in diffs):
                result["wilcoxon_pvalue"] = 1.0
            else:
                result["wilcoxon_pvalue"] = stats.wilcoxon(diffs).pvalue
        except Exception:
            result["wilcoxon_pvalue"] = None

    return result


def build_significance_rows(
    paired_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    rows.append(_paired_test_result("overall_all_docs", paired_rows))

    for evaluation_set in ("main_or_unknown", "stress"):
        subset = [row for row in paired_rows if row["evaluation_set"] == evaluation_set]
        if subset:
            rows.append(_paired_test_result(f"evaluation_set:{evaluation_set}", subset))

    for length_bucket in MAIN_LENGTH_BUCKETS:
        subset = [
            row
            for row in paired_rows
            if row["evaluation_set"] == "main_or_unknown" and row["length_bucket"] == length_bucket
        ]
        if subset:
            rows.append(_paired_test_result(f"length_bucket:{length_bucket}", subset))

    dataset_names = sorted({row["dataset_name"] for row in paired_rows})
    for dataset_name in dataset_names:
        subset = [row for row in paired_rows if row["dataset_name"] == dataset_name]
        if subset:
            rows.append(_paired_test_result(f"dataset:{dataset_name}", subset))
        for length_bucket in MAIN_LENGTH_BUCKETS:
            cell_subset = [
                row
                for row in subset
                if row["evaluation_set"] == "main_or_unknown" and row["length_bucket"] == length_bucket
            ]
            if cell_subset:
                rows.append(
                    _paired_test_result(
                        f"dataset:{dataset_name}|length_bucket:{length_bucket}",
                        cell_subset,
                    )
                )

    return rows


def build_diff_heatmap_rows(paired_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str], list[float]] = defaultdict(list)
    for row in paired_rows:
        if row["evaluation_set"] != "main_or_unknown":
            continue
        key = (row["dataset_name"], row["length_bucket"])
        grouped[key].append(row["diff_lightrag_minus_vector"])

    output: list[dict[str, Any]] = []
    for dataset_name, length_bucket in sorted(grouped):
        output.append(
            {
                "dataset_name": dataset_name,
                "length_bucket": length_bucket,
                "mean_diff_lightrag_minus_vector": mean_or_none(grouped[(dataset_name, length_bucket)]),
                "paired_doc_count": len(grouped[(dataset_name, length_bucket)]),
            }
        )
    return output


def plot_main_metric_by_length_bucket(
    doc_rows: list[dict[str, Any]],
    metric_name: str,
    path: Path,
) -> None:
    filtered = [
        row
        for row in doc_rows
        if row["evaluation_set"] == "main_or_unknown" and row["length_bucket"] in MAIN_LENGTH_BUCKETS
    ]
    if not filtered:
        return

    plt.figure(figsize=(8, 5))
    for system in SYSTEMS:
        ys = []
        for bucket in MAIN_LENGTH_BUCKETS:
            values = [
                row[metric_name]
                for row in filtered
                if row["system"] == system and row["length_bucket"] == bucket and row[metric_name] is not None
            ]
            ys.append(mean_or_none(values) or 0.0)
        plt.plot(
            MAIN_LENGTH_BUCKETS,
            ys,
            marker="o",
            linewidth=2.5,
            color=SYSTEM_COLORS[system],
            label=SYSTEM_LABELS[system],
        )

    plt.ylim(0, 1)
    plt.ylabel(metric_name)
    plt.xlabel("Length Bucket")
    plt.title(f"{metric_name} by Length Bucket")
    plt.grid(axis="y", linestyle="--", alpha=0.35)
    plt.legend()
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def plot_main_metric_by_dataset(
    doc_rows: list[dict[str, Any]],
    metric_name: str,
    path: Path,
) -> None:
    filtered = [row for row in doc_rows if row["evaluation_set"] == "main_or_unknown"]
    datasets = sorted({row["dataset_name"] for row in filtered})
    if not datasets:
        return

    xs = list(range(len(datasets)))
    width = 0.38
    plt.figure(figsize=(max(8, len(datasets) * 1.4), 5))

    for offset, system in ((-width / 2, "vector"), (width / 2, "lightrag")):
        ys = []
        for dataset_name in datasets:
            values = [
                row[metric_name]
                for row in filtered
                if row["dataset_name"] == dataset_name
                and row["system"] == system
                and row[metric_name] is not None
            ]
            ys.append(mean_or_none(values) or 0.0)
        plt.bar(
            [x + offset for x in xs],
            ys,
            width=width,
            color=SYSTEM_COLORS[system],
            label=SYSTEM_LABELS[system],
        )

    plt.xticks(xs, datasets, rotation=15)
    plt.ylim(0, 1)
    plt.ylabel(metric_name)
    plt.xlabel("Dataset")
    plt.title(f"{metric_name} by Dataset")
    plt.grid(axis="y", linestyle="--", alpha=0.35)
    plt.legend()
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def plot_diff_heatmap(
    diff_rows: list[dict[str, Any]],
    path: Path,
) -> None:
    datasets = sorted({row["dataset_name"] for row in diff_rows})
    if not datasets:
        return

    matrix: list[list[float]] = []
    for dataset_name in datasets:
        row_values = []
        for bucket in MAIN_LENGTH_BUCKETS:
            value = next(
                (
                    item["mean_diff_lightrag_minus_vector"]
                    for item in diff_rows
                    if item["dataset_name"] == dataset_name and item["length_bucket"] == bucket
                ),
                0.0,
            )
            row_values.append(value or 0.0)
        matrix.append(row_values)

    plt.figure(figsize=(8, max(4, len(datasets) * 0.6)))
    im = plt.imshow(matrix, cmap="RdBu_r", aspect="auto")
    plt.colorbar(im, label="LightRAG - VectorRAG")
    plt.xticks(range(len(MAIN_LENGTH_BUCKETS)), MAIN_LENGTH_BUCKETS)
    plt.yticks(range(len(datasets)), datasets)
    plt.title("Mean Paired Difference by Dataset and Length Bucket")

    for y, dataset_name in enumerate(datasets):
        for x, bucket in enumerate(MAIN_LENGTH_BUCKETS):
            value = matrix[y][x]
            plt.text(x, y, f"{value:.3f}", ha="center", va="center", fontsize=9)

    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def plot_doc_diff_histogram(
    paired_rows: list[dict[str, Any]],
    path: Path,
) -> None:
    diffs = [row["diff_lightrag_minus_vector"] for row in paired_rows]
    if not diffs:
        return

    plt.figure(figsize=(7, 4.5))
    plt.hist(diffs, bins=min(20, max(5, len(diffs))), color="#7b8fa1", edgecolor="white")
    plt.axvline(0.0, color="black", linestyle="--", linewidth=1.5)
    plt.xlabel("LightRAG - VectorRAG")
    plt.ylabel("Document Count")
    plt.title("Distribution of Paired Document-Level Differences")
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def plot_doc_length_scatter(
    detail_rows: list[dict[str, Any]],
    metric_name: str,
    path: Path,
) -> None:
    if not detail_rows:
        return

    plt.figure(figsize=(8, 5))
    for system in SYSTEMS:
        xs = [row["doc_length_tokens"] for row in detail_rows if row["system"] == system]
        ys = [row[metric_name] for row in detail_rows if row["system"] == system and row[metric_name] is not None]
        paired_points = [
            (row["doc_length_tokens"], row[metric_name])
            for row in detail_rows
            if row["system"] == system and row[metric_name] is not None
        ]
        if not paired_points:
            continue
        plt.scatter(
            [point[0] for point in paired_points],
            [point[1] for point in paired_points],
            s=28,
            alpha=0.65,
            color=SYSTEM_COLORS[system],
            label=SYSTEM_LABELS[system],
        )

    plt.xscale("log")
    plt.ylim(0, 1)
    plt.xlabel("Document Length Tokens (log scale)")
    plt.ylabel(metric_name)
    plt.title(f"{metric_name} vs Document Length")
    plt.grid(linestyle="--", alpha=0.3)
    plt.legend()
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def plot_all_experiments_token_length_scatter(
    doc_points: list[dict[str, Any]],
    metric_name: str,
    path: Path,
) -> None:
    if not doc_points:
        return

    plt.figure(figsize=(9, 5.5))

    for system in SYSTEMS:
        system_points = [
            row
            for row in doc_points
            if row["system"] == system and row.get(metric_name) is not None
        ]
        if not system_points:
            continue

        for source in ("main", "stress", "ultra"):
            subset = [row for row in system_points if row["experiment_source"] == source]
            if not subset:
                continue
            plt.scatter(
                [row["doc_length_tokens"] for row in subset],
                [row[metric_name] for row in subset],
                s=38,
                alpha=0.72,
                color=SYSTEM_COLORS[system],
                marker=EXPERIMENT_MARKERS[source],
                label=f"{SYSTEM_LABELS[system]} ({source})",
            )

        if len(system_points) >= 2:
            aligned = [
                (math.log10(row["doc_length_tokens"]), row[metric_name], row["doc_length_tokens"])
                for row in system_points
                if row["doc_length_tokens"] > 0
            ]
            if len(aligned) >= 2:
                aligned.sort(key=lambda item: item[0])
                x_vals = [item[0] for item in aligned]
                y_vals = [item[1] for item in aligned]
                slope, intercept = statistics.linear_regression(x_vals, y_vals)
                x_min = min(item[2] for item in aligned)
                x_max = max(item[2] for item in aligned)
                line_x = [x_min, x_max]
                line_y = [slope * math.log10(x) + intercept for x in line_x]
                plt.plot(
                    line_x,
                    line_y,
                    color=SYSTEM_COLORS[system],
                    linewidth=2.6,
                    alpha=0.95,
                )

    plt.xscale("log")
    plt.ylim(0, 1)
    plt.xlabel("Document Length Tokens (log scale)")
    plt.ylabel(metric_name)
    plt.title(f"{metric_name} vs Document Length (All Experiments)")
    plt.grid(linestyle="--", alpha=0.25)
    plt.legend(ncol=2, fontsize=9)
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def extract_usage_proxy(usage: Any) -> float:
    if not isinstance(usage, dict):
        return 0.0

    if isinstance(usage.get("total_tokens"), (int, float)):
        return float(usage["total_tokens"])

    prompt_completion_keys = ("prompt_tokens", "completion_tokens")
    if any(isinstance(usage.get(key), (int, float)) for key in prompt_completion_keys):
        return float(sum(float(usage.get(key, 0)) for key in prompt_completion_keys))

    input_output_keys = ("input_tokens", "output_tokens")
    if any(isinstance(usage.get(key), (int, float)) for key in input_output_keys):
        return float(sum(float(usage.get(key, 0)) for key in input_output_keys))

    if any(key.startswith("main_estimated_") for key in usage):
        return float(
            sum(
                float(value)
                for key, value in usage.items()
                if key.startswith("main_estimated_") and isinstance(value, (int, float))
            )
        )

    estimated_keys = (
        "estimated_embedding_input_tokens",
        "estimated_document_tokens",
        "estimated_question_tokens",
        "estimated_retrieved_context_tokens",
        "estimated_answer_tokens",
    )
    return float(
        sum(float(usage.get(key, 0)) for key in estimated_keys if isinstance(usage.get(key), (int, float)))
    )


def load_cost_proxy_rows(token_usage_jsonl: Path) -> list[dict[str, Any]]:
    if not token_usage_jsonl.exists():
        return []

    grouped: dict[tuple[str, str], dict[str, Any]] = {}

    with token_usage_jsonl.open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            event = json.loads(raw)
            doc_id = str(event.get("doc_id") or "")
            dataset_name = str(event.get("dataset_name") or "")
            if not doc_id:
                continue
            key = (dataset_name, doc_id)
            if key not in grouped:
                grouped[key] = {
                    "dataset_name": dataset_name,
                    "doc_id": doc_id,
                    "vector_build_tokens_proxy": 0.0,
                    "vector_query_tokens_proxy": 0.0,
                    "lightrag_build_tokens_proxy": 0.0,
                    "lightrag_query_tokens_proxy": 0.0,
                }

            entry = grouped[key]
            event_type = event.get("event_type")
            if event_type == "document_build":
                entry["vector_build_tokens_proxy"] += extract_usage_proxy(event.get("vector_build_usage"))
                entry["lightrag_build_tokens_proxy"] += extract_usage_proxy(
                    event.get("lightrag_build_usage")
                )
            elif event_type == "qa_query":
                entry["vector_query_tokens_proxy"] += extract_usage_proxy(
                    event.get("vector_query_usage")
                )
                entry["lightrag_query_tokens_proxy"] += extract_usage_proxy(
                    event.get("lightrag_query_usage")
                )

    rows: list[dict[str, Any]] = []
    for entry in grouped.values():
        rows.append(
            {
                "dataset_name": entry["dataset_name"],
                "doc_id": entry["doc_id"],
                "system": "vector",
                "build_tokens_proxy": entry["vector_build_tokens_proxy"],
                "query_tokens_proxy": entry["vector_query_tokens_proxy"],
                "total_tokens_proxy": entry["vector_build_tokens_proxy"]
                + entry["vector_query_tokens_proxy"],
            }
        )
        rows.append(
            {
                "dataset_name": entry["dataset_name"],
                "doc_id": entry["doc_id"],
                "system": "lightrag",
                "build_tokens_proxy": entry["lightrag_build_tokens_proxy"],
                "query_tokens_proxy": entry["lightrag_query_tokens_proxy"],
                "total_tokens_proxy": entry["lightrag_build_tokens_proxy"]
                + entry["lightrag_query_tokens_proxy"],
            }
        )
    return rows


def join_cost_proxy(
    doc_rows: list[dict[str, Any]],
    cost_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    by_key = {
        (row["dataset_name"], row["doc_id"], row["system"]): row
        for row in cost_rows
    }
    joined: list[dict[str, Any]] = []
    for row in doc_rows:
        item = dict(row)
        cost = by_key.get((row["dataset_name"], row["doc_id"], row["system"]))
        if cost is not None:
            item.update(
                {
                    "build_tokens_proxy": cost["build_tokens_proxy"],
                    "query_tokens_proxy": cost["query_tokens_proxy"],
                    "total_tokens_proxy": cost["total_tokens_proxy"],
                }
            )
        else:
            item.update(
                {
                    "build_tokens_proxy": None,
                    "query_tokens_proxy": None,
                    "total_tokens_proxy": None,
                }
            )
        joined.append(item)
    return joined


def plot_cost_quality_tradeoff(
    doc_rows_with_cost: list[dict[str, Any]],
    metric_name: str,
    path: Path,
) -> None:
    points = [
        row
        for row in doc_rows_with_cost
        if row.get("total_tokens_proxy") not in (None, 0) and row.get(metric_name) is not None
    ]
    if not points:
        return

    plt.figure(figsize=(8, 5))
    for system in SYSTEMS:
        system_points = [row for row in points if row["system"] == system]
        if not system_points:
            continue
        plt.scatter(
            [row["total_tokens_proxy"] for row in system_points],
            [row[metric_name] for row in system_points],
            s=28,
            alpha=0.65,
            color=SYSTEM_COLORS[system],
            label=SYSTEM_LABELS[system],
        )

    plt.xscale("log")
    plt.ylim(0, 1)
    plt.xlabel("Total Tokens Proxy (log scale)")
    plt.ylabel(metric_name)
    plt.title(f"{metric_name} vs Cost Proxy")
    plt.grid(linestyle="--", alpha=0.3)
    plt.legend()
    ensure_parent_dir(path)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def build_summary_payload(
    *,
    metric_name: str,
    paired_rows: list[dict[str, Any]],
    cost_available: bool,
) -> dict[str, Any]:
    diffs = [row["diff_lightrag_minus_vector"] for row in paired_rows]
    return {
        "main_metric": metric_name,
        "paired_doc_count": len(paired_rows),
        "mean_diff_lightrag_minus_vector": mean_or_none(diffs),
        "median_diff_lightrag_minus_vector": statistics.median(diffs) if diffs else None,
        "cost_proxy_available": cost_available,
    }


def main() -> None:
    args = parse_args()
    evaluation_dir = args.evaluation_dir
    output_dir = args.output_dir or (evaluation_dir / "analysis")
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"

    detail_rows_raw = load_csv_rows(evaluation_dir / "evaluation_details.csv")
    doc_rows_raw = load_csv_rows(evaluation_dir / "evaluation_doc_summary.csv")

    detail_rows = flatten_detail_rows(detail_rows_raw)
    doc_rows = flatten_doc_rows(doc_rows_raw)

    metric_fields = [
        args.main_metric,
        "exact_match",
        "answer_accuracy",
        "faithfulness",
        "response_relevancy",
        "retrieval_quality_score",
        "overall_quality_score",
    ]
    metric_fields = list(dict.fromkeys(metric_fields))

    overall_rows = aggregate_rows(
        doc_rows,
        group_fields=["system"],
        metric_fields=metric_fields,
        extra_fields=["avg_error_question_rate", "avg_numeric_question_share"],
    )
    for row in overall_rows:
        row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
    write_table_bundle(tables_dir / "table_overall_system_comparison", overall_rows)

    bucket_rows = aggregate_rows(
        [row for row in doc_rows if row["evaluation_set"] in {"main_or_unknown", "stress"}],
        group_fields=["system", "evaluation_set", "length_bucket"],
        metric_fields=metric_fields,
        extra_fields=["avg_error_question_rate", "avg_numeric_question_share"],
    )
    for row in bucket_rows:
        row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
    write_table_bundle(tables_dir / "table_by_length_bucket", bucket_rows)

    dataset_rows = aggregate_rows(
        doc_rows,
        group_fields=["system", "dataset_name", "evaluation_set"],
        metric_fields=metric_fields,
        extra_fields=["avg_error_question_rate", "avg_numeric_question_share"],
    )
    for row in dataset_rows:
        row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
    write_table_bundle(tables_dir / "table_by_dataset", dataset_rows)

    pre_formula_dataset_rows = aggregate_rows(
        doc_rows,
        group_fields=["system", "dataset_name", "evaluation_set"],
        metric_fields=PRE_FORMULA_ANSWER_METRICS,
        extra_fields=["avg_numeric_question_share"],
    )
    for row in pre_formula_dataset_rows:
        row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
    write_table_bundle(
        tables_dir / "table_pre_formula_answer_metrics_by_dataset",
        pre_formula_dataset_rows,
    )

    question_type_rows = aggregate_rows(
        detail_rows,
        group_fields=["system", "question_type"],
        metric_fields=metric_fields,
    )
    for row in question_type_rows:
        row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
    write_table_bundle(tables_dir / "table_by_question_type", question_type_rows)

    paired_rows = pair_doc_metric_rows(doc_rows, args.main_metric)
    significance_rows = build_significance_rows(paired_rows)
    write_table_bundle(tables_dir / "table_significance_tests", significance_rows)

    diff_heatmap_rows = build_diff_heatmap_rows(paired_rows)
    write_table_bundle(tables_dir / "table_dataset_bucket_differences", diff_heatmap_rows)

    plot_main_metric_by_length_bucket(
        doc_rows,
        args.main_metric,
        figures_dir / "figure_main_metric_by_length_bucket_binned.png",
    )
    plot_main_metric_by_dataset(
        doc_rows,
        args.main_metric,
        figures_dir / "figure_main_metric_by_dataset.png",
    )
    plot_diff_heatmap(
        diff_heatmap_rows,
        figures_dir / "figure_dataset_bucket_difference_heatmap.png",
    )
    plot_doc_diff_histogram(
        paired_rows,
        figures_dir / "figure_doc_difference_histogram.png",
    )
    plot_doc_length_scatter(
        detail_rows,
        args.main_metric,
        figures_dir / "figure_doc_length_scatter.png",
    )

    merged_detail_rows = load_merged_detail_rows(
        evaluation_dir,
        args.extra_evaluation_dirs,
    )
    all_experiment_doc_points = build_doc_metric_points(
        merged_detail_rows,
        args.main_metric,
    )
    plot_all_experiments_token_length_scatter(
        all_experiment_doc_points,
        args.main_metric,
        figures_dir / "figure_main_metric_by_length_bucket.png",
    )

    cost_rows = load_cost_proxy_rows(args.token_usage_jsonl)
    if cost_rows:
        doc_rows_with_cost = join_cost_proxy(doc_rows, cost_rows)
        cost_table_rows = aggregate_rows(
            [row for row in doc_rows_with_cost if row.get("total_tokens_proxy") is not None],
            group_fields=["system", "dataset_name"],
            metric_fields=[args.main_metric],
            extra_fields=["build_tokens_proxy", "query_tokens_proxy", "total_tokens_proxy"],
        )
        for row in cost_table_rows:
            row["system"] = SYSTEM_LABELS.get(row["system"], row["system"])
        write_table_bundle(tables_dir / "table_cost_proxy", cost_table_rows)
        plot_cost_quality_tradeoff(
            doc_rows_with_cost,
            args.main_metric,
            figures_dir / "figure_cost_quality_tradeoff.png",
        )

    summary_payload = build_summary_payload(
        metric_name=args.main_metric,
        paired_rows=paired_rows,
        cost_available=bool(cost_rows),
    )
    ensure_parent_dir(output_dir / "analysis_summary.json")
    (output_dir / "analysis_summary.json").write_text(
        json.dumps(summary_payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
